DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	user_name VARCHAR(100),
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL
);